server:
  port: 8082

spring:
  application:
    name: projeto-pratico-pjcmt
  datasource:
    url: jdbc:postgresql://postgres:5433/projeto_pratico
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs-ui.html

minio:
  access-key: 'xDM3aBJsyqpiYrkUbzse'
  secret-key: 'qJxpxbSigrL0vTs2E1O4WKFMYkFS36E7ILMFDTu3'
  buckets:
    foto: foto-pessoa
  endpoint: 'http://localhost:9000'