server:
  port: 8082

spring:
  application:
    name: projeto-pratico-pjcmt
  datasource:
    url: jdbc:postgresql://postgres:5433/projeto_pratico
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    codec:
      max-in-memory-size: 10MB

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs-ui.html

minio:
  access-key: 'MrH4MEHUqxNt4TIDJNcK'
  secret-key: 'lBYkT16hedaBrCj2xTT6TT0fHf6QsHDsiDfIOgsZ'
  buckets:
    bucketFotoPessoa: foto-pessoa
  endpoint: 'http://localhost:9000'